[package]
name = "rust_ray_tracing"
version = "0.1.0"
authors = ["Christopher Webb <christopher.webb@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
num_cpus = "1.0"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0"
clap = "2.33.0"
indicatif = "0.13.0"
